# Generated by Django 5.2 on 2025-05-17 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UrlModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url", models.URLField(max_length=256, verbose_name="Original URL")),
                (
                    "short_code",
                    models.CharField(
                        editable=False, unique=True, verbose_name="Short Code"
                    ),
                ),
                (
                    "access_count",
                    models.PositiveIntegerField(default=0, verbose_name="Access Count"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user added url",
                    ),
                ),
            ],
            options={
                "verbose_name": "URL",
                "verbose_name_plural": "URLs",
                "ordering": ["-created_at"],
            },
        ),
    ]
